name: Deploy Staging - Surge.sh

on:
  push:
    branches:
    - 'develop'

env:
  NODE: 16
  SURGE_STAGING_DOMAIN: https://visex.surge.sh

jobs:
  build:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      # See comment on checks-yml - prep step
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get submodules
        env:
          SSH_KEY_SUBMODULE: ${{secrets.DELTA_UI_FETCH_KEY}}
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${SSH_KEY_SUBMODULE}"; git submodule update --init --recursive

      - name: Use Node.js ${{ env.NODE }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE }}

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: |
            node_modules
            .delta/ui/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}

      - name: Cache dist
        uses: actions/cache@v2
        id: cache-dist
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.workflow }}-${{ github.sha }}

      - name: Install
        run: ./.delta/setup

      - name: Build staging
        run: yarn stage

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # See comment on checks-yml - prep step
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get submodules
        env:
          SSH_KEY_SUBMODULE: ${{secrets.DELTA_UI_FETCH_KEY}}
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${SSH_KEY_SUBMODULE}"; git submodule update --init --recursive
      - name: Restore node_modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: |
            node_modules
            .delta/ui/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}

      - name: Restore dist cache
        uses: actions/cache@v2
        id: cache-dist
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.workflow }}-${{ github.sha }}

      - name: Use Node.js ${{ env.NODE }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE }}

      - name: Deploy Staging to Surge
        run: |
          cp ./dist/index.html ./dist/200.html
          yarn run surge ./dist ${{ env.SURGE_STAGING_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
